### ISSUE TITLE
RTAndroid

### ISSUE THREAD

**Issue by khannover** [blackout314/awesome-raspberry-pi#6]
Hi,

do you know RT Android ( https://git.embedded.rwth-aachen.de/rtandroid/ ) ?
Maybe it makes sense to add this to the android section.
I am sure that many people would like to try to run android don a raspberry.

**Comment by blackout314** [comment]
open a pull request and i add ^_^

**Comment by blackout314** [comment]
i think is usefull, create android section and add this project 👍
