### ISSUE TITLE
Page not found on raspberry pi solar tracker

### ISSUE THREAD

**Issue by dcast78** [blackout314/awesome-raspberry-pi#8]
The project raspberry pi solar tracker return page not found at
http://polyideas.com/blog/2015/8/18/raspberry-pi-solar-tracker

**Comment by blackout314** [comment]
i try to search it on web archive

**Comment by blackout314** [comment]
https://web.archive.org/web/20150921165758/http://polyideas.com/blog/2015/8/18/raspberry-pi-solar-tracker

but no photos..
